
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int id = 5;
  public static final int notacion = 7;
  public static final int dpuntos = 4;
  public static final int cadena = 10;
  public static final int pcoma = 8;
  public static final int conj = 3;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int flecha = 6;
  public static final int dosporcentajes = 9;
  public static final int parentesisa = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "parentesisa",
  "conj",
  "dpuntos",
  "id",
  "flecha",
  "notacion",
  "pcoma",
  "dosporcentajes",
  "cadena"
  };
}

